/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * Jframemain.java
 *
 * Created on May 3, 2012, 11:30:17 AM
 */
package goal.keeper;

/**
 *
 * @author Gautam krishna.R
 */
public class Jframemain extends javax.swing.JFrame {

    /** Creates new form Jframemain */
    public Jframemain() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        d1 = new javax.swing.JDialog();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        gn = new javax.swing.JTextField();
        gnn = new javax.swing.JLabel();
        rtx2 = new javax.swing.JLabel();
        tAGoals = new javax.swing.JLabel();
        tBGoals = new javax.swing.JLabel();
        decRes = new javax.swing.JButton();
        GoalOfA = new javax.swing.JButton();
        GoalOfB = new javax.swing.JButton();
        result = new javax.swing.JLabel();
        t11 = new javax.swing.JLabel();
        t22 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        d1.setTitle("Team name");
        d1.setAlwaysOnTop(true);
        d1.setBounds(new java.awt.Rectangle(0, 0, 225, 200));
        d1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        d1.setResizable(false);

        t1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t1.setText("A");
        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        t2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        t2.setText("B");
        t2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t2ActionPerformed(evt);
            }
        });

        jButton2.setText("OK");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Team Name");

        gn.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        gn.setText("FOOT BALL MATCH");
        gn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout d1Layout = new javax.swing.GroupLayout(d1.getContentPane());
        d1.getContentPane().setLayout(d1Layout);
        d1Layout.setHorizontalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(d1Layout.createSequentialGroup()
                .addGroup(d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, d1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, d1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(t1, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, d1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(gn))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, d1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(t2, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)))
                    .addGroup(d1Layout.createSequentialGroup()
                        .addGap(84, 84, 84)
                        .addComponent(jButton2)))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        d1Layout.setVerticalGroup(
            d1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, d1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addComponent(gn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(23, 23, 23))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        gnn.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        gnn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        gnn.setText("FOOT BALL MATCH");
        gnn.setAlignmentY(0.0F);

        rtx2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        rtx2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        rtx2.setText("Score Board");
        rtx2.setAlignmentY(0.0F);

        tAGoals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tAGoals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tAGoals.setText("0");
        tAGoals.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        tAGoals.setVerifyInputWhenFocusTarget(false);

        tBGoals.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        tBGoals.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        tBGoals.setText("0");
        tBGoals.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 6, true));
        tBGoals.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        decRes.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        decRes.setText("Decalare Result");
        decRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                decResActionPerformed(evt);
            }
        });

        GoalOfA.setText("+1");
        GoalOfA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoalOfAActionPerformed(evt);
            }
        });

        GoalOfB.setText("+1");
        GoalOfB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoalOfBActionPerformed(evt);
            }
        });

        result.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        result.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(51, 0, 255), 1, true));

        t11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t11.setText("A");

        t22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        t22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        t22.setText("B");

        jButton1.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jButton1.setText("Edit teams & details");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jButton1))
                    .addComponent(rtx2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(GoalOfA)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(result, javax.swing.GroupLayout.DEFAULT_SIZE, 285, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(GoalOfB))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(t11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(decRes)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(t22, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tBGoals, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)))
                    .addComponent(gnn, javax.swing.GroupLayout.DEFAULT_SIZE, 387, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(gnn)
                .addGap(18, 18, 18)
                .addComponent(rtx2)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t22)
                            .addComponent(t11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tBGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tAGoals, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(decRes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(GoalOfB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(GoalOfA))
                    .addComponent(result, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

private void decResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_decResActionPerformed
int ga=Integer.parseInt(tAGoals.getText());
int gb=Integer.parseInt(tBGoals.getText());
if(ga>gb)
    result.setText("Team "+t11.getText()+" Wins");
else if(ga<gb)
    result.setText("Team "+t22.getText()+" Wins");
else
    result.setText("The game is a tie");
}//GEN-LAST:event_decResActionPerformed

private void GoalOfAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoalOfAActionPerformed
String v1=tAGoals.getText();
int ga=Integer.parseInt(v1);
ga=ga+1;
tAGoals.setText(""+ga);
}//GEN-LAST:event_GoalOfAActionPerformed

private void GoalOfBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoalOfBActionPerformed
String v1=tBGoals.getText();
int gb=Integer.parseInt(v1);
gb=gb+1;
tBGoals.setText(""+gb);
}//GEN-LAST:event_GoalOfBActionPerformed

private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
// TODO add your handling code here:
    d1.setVisible(true);
}//GEN-LAST:event_jButton1ActionPerformed

private void t2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t2ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t2ActionPerformed

private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
// TODO add your handling code here:
    String a=gn.getText();
    a=a.toUpperCase();
    gn.setText(a);
    a=t1.getText();
    a=a.toUpperCase();
    t1.setText(a);
    a=t2.getText();
    a=a.toUpperCase();
    t2.setText(a);
    t11.setText(""+t1.getText());
    t22.setText(""+t2.getText());
    gnn.setText(""+gn.getText());
    d1.setVisible(false);
}//GEN-LAST:event_jButton2ActionPerformed

private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_t1ActionPerformed

private void gnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gnActionPerformed
// TODO add your handling code here:
}//GEN-LAST:event_gnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jframemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jframemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jframemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jframemain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new Jframemain().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton GoalOfA;
    private javax.swing.JButton GoalOfB;
    private javax.swing.JDialog d1;
    private javax.swing.JButton decRes;
    private javax.swing.JTextField gn;
    private javax.swing.JLabel gnn;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel result;
    private javax.swing.JLabel rtx2;
    private javax.swing.JTextField t1;
    private javax.swing.JLabel t11;
    private javax.swing.JTextField t2;
    private javax.swing.JLabel t22;
    private javax.swing.JLabel tAGoals;
    private javax.swing.JLabel tBGoals;
    // End of variables declaration//GEN-END:variables
}
